import React,{useState,useEffect} from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Button from '../lib/buttons/Button'
import AlignItems from '../lib/style/AlignItems';

import { FiLogIn,FiBookOpen } from "react-icons/fi";
import { useRouter } from 'next/router';

import {app} from '../firebase'
import { getAuth, signInWithGoogle } from 'firebase/auth';
import { useAuthState, useSignInWithGoogle } from 'react-firebase-hooks/auth';
import LoadingBar from 'react-top-loading-bar';

export default function Home() {
  const router = useRouter();

  const auth = getAuth(app);
  const [signInWithGoogle] = useSignInWithGoogle(auth);
  const [user, loading, error] = useAuthState(auth);

  const [progress, setProgress] = useState(0)

  useEffect(() => {
    if (user) {
      setProgress(30);
      router.push('/app');
    }
  }, [user])
  

  return (
    <>
      <LoadingBar
        color='var(--accentColor)'
        progress={progress}
        onLoaderFinished={() => setProgress(0)}
        waitingTime={500}
      />
      <Head>
        <title>Kashidashi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AlignItems flexDirection={"column"}>
          <h1 style={{fontSize:'3em',marginBottom:'0.5em'}}>
            Kashidashi
          </h1>
          <h3>貸出しの管理をもっとシンプルに。</h3>
          <AlignItems>
            <Button accentColor={true} icon={<FiLogIn/>} onClick={()=>signInWithGoogle()}>Googleでログイン</Button>
            <Button icon={<FiBookOpen/>} onClick={()=>router.push('/about')}>Kashidashiについて</Button>
          </AlignItems>
        </AlignItems>
        <div>
          <h1>About</h1>
        </div>
      </main>
    </>
  )
}
